// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqT_QGEcnR5cnC2DvmVQB7SHI2ZD8XpqM',
    appId: '1:482988523889:web:20064a3466cdac0ce436d0',
    messagingSenderId: '482988523889',
    projectId: 'onlook-9f3d2',
    authDomain: 'onlook-9f3d2.firebaseapp.com',
    storageBucket: 'onlook-9f3d2.appspot.com',
    measurementId: 'G-B84JRS4FFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUxePKoxaGTOf0c1kBK9WDRz3jHFmYfsA',
    appId: '1:482988523889:android:687b8acf2a656146e436d0',
    messagingSenderId: '482988523889',
    projectId: 'onlook-9f3d2',
    storageBucket: 'onlook-9f3d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuOZFKy9QX_U84DeUy_QfDrhlBYP7hy_4',
    appId: '1:482988523889:ios:a54ab70e1d605200e436d0',
    messagingSenderId: '482988523889',
    projectId: 'onlook-9f3d2',
    storageBucket: 'onlook-9f3d2.appspot.com',
    iosClientId: '482988523889-8mv77s68sjtjci4305o5kdl1adr7f33m.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuOZFKy9QX_U84DeUy_QfDrhlBYP7hy_4',
    appId: '1:482988523889:ios:a54ab70e1d605200e436d0',
    messagingSenderId: '482988523889',
    projectId: 'onlook-9f3d2',
    storageBucket: 'onlook-9f3d2.appspot.com',
    iosClientId: '482988523889-8mv77s68sjtjci4305o5kdl1adr7f33m.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
